complexity: 3
maxTransactionsPerBlock: 2

## node
host: https://localhost
port: 8081
nodeDistributionTimeOut: 30
knownNodes:
  - https://localhost:8081
  - https://localhost:8082

## block
blockDistributionTimeout: 30
blockInquiryTimeOut: 30
secretDir: secrets

## genesis
inGenesis: true