complexity: 3
maxTransactionsPerBlock: 2

## node
host: https://localhost
port: 8083
nodeDistributionTimeOut: 300
knownNodes:
  - ip: https://localhost:8080
    certificatePath: "secrets/node1/cert.pem"
    address: "00797d792e81e4bc6e696bbfcdbdeba03e15a93c"
  - ip: https://localhost:8082
    certificatePath: "secrets/node3/cert.pem"
    address: "463a35f25437678996041fb93fcb87bf8d86ac98"
## block
blockDistributionTimeout: 300
blockInquiryTimeOut: 30
secretDir: secrets/node4

## genesis
inGenesis: false