complexity: 3
maxTransactionsPerBlock: 2

## node
host: http://localhost
port: 8080
nodeDistributionTimeOut: 30
knownNodes:
  - http://localhost:8081
  - http://localhost:8082

## block
blockDistributionTimeout: 30