complexity: 3
maxTransactionsPerBlock: 2

## node
host: http://localhost
port: 8082
nodeDistributionTimeOut: 300
knownNodes:
  - http://localhost:8080
  - http://localhost:8081

## block
blockDistributionTimeout: 300
blockInquiryTimeOut: 30